### ISSUE TITLE
Add option to hide timestamps on right side of emails in inbox/list

### ISSUE THREAD

**Issue by russelldc** [boukestam/inbox-in-gmail#75]
This is mostly just a reminder for myself to complete this, not a request.

The original Inbox webapp was as simple as possible, it didn't even show the date/timestamp on the right side of each email in the inbox (or other folders).

I've seen a few people ask for this in reviews, and I'd wanted this as well. Now that we have the extension options menu, I'll go ahead and add it, and default to show timestamp.

----------

Some old notes I had of how to accomplish this:

```css
/* Hide the time/date completely */
.zA .yf.xY, .zA .xW.xY {
  display: none;
}

/* Set positioning of pin to relative, to the right side */
.zA .apU.xY {
  position: relative;
  order: 2;
  margin-right: 0;
  padding-right: 0;
}

/* Add a little padding to the right of email content excerpt */
.zA > .a4W {
  padding-right: 25px;
}

/* Reduce padding on right side of snooze icon (might not be relevant with recent changes) */
.zA .xY.byZ {
  padding-right: 12px !important;
}
```
