### ISSUE TITLE
Font should be Helvetica, rather than Roboto

### ISSUE THREAD

**Issue by russelldc** [boukestam/inbox-in-gmail#8]
A review left on the Chrome Web Store mentioned this:

> A few suggestions: first, while Gmail uses the Roboto font, Inbox uses Helvetica (and a slightly smaller font size). It would be great if the extension switched the font to Helvetica and to the same font size as Inbox. Second, it'd be nice of the blue header cast a shadow like in Inbox.
- Jennifer Carr

And she supplied this css:

```css
* {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 99.1%;
    letter-spacing: normal; 
}

/* Email subject colour */
.zA {
    color: #040404;
}

header {
    box-shadow: 0 0 4px rgba(0,0,0,.14), 0 4px 8px rgba(0,0,0,.28);
}

a.gb_de {
    font-family: "Product Sans" !important;
}
```
